### ISSUE TITLE
OSError: [Errno 8] Exec format error: '/home/root/ML-web-app/app/app.py'

### ISSUE THREAD

**Issue by viniedodo** [imadelh/ML-web-app#1]
root@jetson:~/ML-web-app/app# python3 app.py
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:8889/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "app.py", line 46, in <module>
    port=PORT)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 944, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 1007, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/root/ML-web-app/app/app.py'
--------------------------------------------------------------------------------------------------------

how can i do?

**Comment by imadelh** [comment]
This is related to flask. From what I am reading on SOF, you need to make the file app.py executable `chmod -x app.py` : https://github.com/pallets/werkzeug/issues/1482#issuecomment-475181497 

Same issue is explained here: https://stackoverflow.com/questions/55315103/oserror-errno-8-exec-format-error-when-trying-to-run-simple-flask-app-in-a/55359108
https://stackoverflow.com/questions/55271912/flask-cli-throws-oserror-errno-8-exec-format-error-when-run-through-docker

**Comment by viniedodo** [comment]
thank you, it worked!

**Comment by Gavin-Evans** [comment]
> thank you, it worked!

hi,
Can you send me a full version of your code? Email: xrinozpg616@gmail.com
thanks,
